#!/bin/bash
# ============================================================
# FamOS First-Time Setup Script
# Run this ONCE on your Linux server to get everything ready.
# Usage: bash setup.sh
# ============================================================

set -e

INSTALL_DIR="/opt/famos/backend"
ENV_FILE="$INSTALL_DIR/.env"

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       FamOS Server Setup             ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ── Step 1: Check Python ────────────────────────────────────
echo "▶ Checking Python..."
if ! command -v python3 &>/dev/null; then
    echo "  ✗ Python3 not found. Install it first:"
    echo "    sudo apt install python3 python3-pip python3-venv"
    exit 1
fi
echo "  ✓ Python $(python3 --version)"

# ── Step 2: Create install dir ──────────────────────────────
echo ""
echo "▶ Preparing directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/secure_uploads"
mkdir -p "$INSTALL_DIR/logs"
mkdir -p "/opt/famos/backups"
echo "  ✓ Directories ready"

# ── Step 3: Python virtual env ──────────────────────────────
echo ""
echo "▶ Setting up Python environment..."
cd "$INSTALL_DIR"
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo "  ✓ Virtual environment created"
else
    echo "  ✓ Virtual environment already exists"
fi

source venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt
echo "  ✓ All dependencies installed"

# ── Step 4: Generate keys ───────────────────────────────────
echo ""
echo "▶ Generating cryptographic keys..."

SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(40))")
JWT_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(40))")
VAULT_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

echo "  ✓ SECRET_KEY generated      (${#SECRET_KEY} chars)"
echo "  ✓ JWT_SECRET_KEY generated  (${#JWT_SECRET_KEY} chars)"
echo "  ✓ VAULT_ENCRYPTION_KEY generated"

# ── Step 5: Write .env ──────────────────────────────────────
echo ""
echo "▶ Creating .env file..."

if [ -f "$ENV_FILE" ]; then
    echo "  ⚠ .env already exists — backing up to .env.bak"
    cp "$ENV_FILE" "$ENV_FILE.bak"
fi

cat > "$ENV_FILE" << EOF
# FamOS Environment Configuration
# Generated by setup.sh on $(date)
# ────────────────────────────────────────────
# NEVER commit this file to git.
# Back up VAULT_ENCRYPTION_KEY somewhere safe!
# ────────────────────────────────────────────

SECRET_KEY=$SECRET_KEY
JWT_SECRET_KEY=$JWT_SECRET_KEY
DATABASE_URI=sqlite:///app.db
VAULT_ENCRYPTION_KEY=$VAULT_KEY
EOF

chmod 600 "$ENV_FILE"
echo "  ✓ .env created at $ENV_FILE (permissions: 600)"

# ── Step 6: Initialize database ────────────────────────────
echo ""
echo "▶ Initializing database..."

python3 - << 'PYEOF'
import sys, os
sys.path.insert(0, '.')
from dotenv import load_dotenv
load_dotenv()

from app import create_app, db
import sqlalchemy

app = create_app()
with app.app_context():
    db.create_all()
    # Enable WAL mode for better performance
    with db.engine.connect() as conn:
        conn.execute(sqlalchemy.text('PRAGMA journal_mode=WAL'))
        conn.execute(sqlalchemy.text('PRAGMA synchronous=NORMAL'))
        conn.execute(sqlalchemy.text('PRAGMA foreign_keys=ON'))
        conn.commit()

print("  ✓ All database tables created")
print("  ✓ SQLite WAL mode enabled")
print(f"  ✓ Database file: {os.path.abspath('instance/app.db')}")
PYEOF

# ── Step 7: Test health endpoint ───────────────────────────
echo ""
echo "▶ Running quick smoke test..."
timeout 8 python3 -c "
from dotenv import load_dotenv; load_dotenv()
from app import create_app, db
app = create_app()
with app.app_context():
    db.session.execute(db.text('SELECT 1'))
    print('  ✓ Database connection: OK')
    from app.models import User, Family, Task, Grocery, Transaction
    print('  ✓ All models accessible')
"

# ── Done ────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  ✅  Setup complete!                         ║"
echo "╠══════════════════════════════════════════════╣"
echo "║                                              ║"
echo "║  ⚠  IMPORTANT — back up these keys now:     ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Your VAULT_ENCRYPTION_KEY (save this somewhere safe):"
echo ""
grep VAULT_ENCRYPTION_KEY "$ENV_FILE"
echo ""
echo "── What to do next ───────────────────────────────"
echo "  1. Start the server:   python run.py"
echo "  2. Test the health:    curl http://localhost:5000/health"
echo "  3. Set up systemd:     see deployment guide"
echo "  4. Start Cloudflare:   cloudflared tunnel run famos-backend"
echo ""
